add_newline = false

[line_break]
disabled = true

[username]
disabled = false
show_always = true

[hostname]
ssh_only = false

[cmd_duration]
min_time = 10000
show_milliseconds = false
disabled = false
